# Generated by Django 2.1.7 on 2019-03-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='servers',
            field=models.ManyToManyField(through='api.Right', to='api.Server'),
        ),
    ]
