# Generated by Django 2.1.7 on 2019-03-13 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_servers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='user_one',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user_two',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_friends_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
