# Generated by Django 2.1.7 on 2019-03-27 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190327_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(through='api.Friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
