# Generated by Django 2.1.7 on 2019-03-27 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='id',
        ),
        migrations.AddField(
            model_name='friend',
            name='chanel',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Channel'),
            preserve_default=False,
        ),
    ]
