# Generated by Django 2.1.7 on 2019-03-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190327_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='direct_type',
            field=models.BooleanField(default=False),
        ),
    ]
